services:
  paperless-frontend:
    container_name: paperless-frontend
    build:
      context: .
      dockerfile: PaperlessWebUI/Dockerfile
    image: paperless-frontend:nginx
    ports:
      - 8080:80
    depends_on:
      - paperless-db
  paperless-rest:
    container_name: paperless-rest-server
    build:
      context: .
      dockerfile: Dockerfile
    image: paperless-rest-server:latest
    ports:
      - 8081:8081
    depends_on:
      - paperless-db

  paperless-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - paperless_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: paperless_db

volumes:
    paperless_data: