version: '3.8'

services:
  paperless-frontend:
    container_name: paperless-frontend
    build:
      context: .
      dockerfile: PaperlessWebUI/Dockerfile
    image: paperless-frontend:nginx
    ports:
      - "8080:80"

  paperless-rest:
    container_name: paperless-rest-server
    build:
      context: .
      dockerfile: Dockerfile
    image: paperless-rest-server:latest
    ports:
      - "8081:8081"
    depends_on:
      - paperless-db

  paperless-db:
    container_name: paperless-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: paperlessdb  # The name of the database to be created
      POSTGRES_USER: admin      # The username for the database
      POSTGRES_PASSWORD: admin  # The password for the user
    volumes:
      - paperless-db-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "9093:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
      - ./init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./init/definitions.json:/etc/rabbitmq/definitions.json

volumes:
  paperless-db-data:
  rabbitmq-data:
  rabbitmq-log: