services:
  paperless-rest:
    container_name: paperless-rest-server
    build:
      context: .
      dockerfile: Dockerfile
    image: paperless-rest-server:latest
    ports:
      - 8081:8081
  paperless-frontend:
    container_name: paperless-frontend
    build:
      context: .
      dockerfile: PaperlessWebUI/Dockerfile
    image: paperless-frontend:nginx
    ports:
      - 8080:80