name: CI/CD Pipeline
run-name: ${{ github.actor }} is running the Pipeline 🚀

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: PaperlessREST

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: maven

    - name: Build and Test
      run: mvn clean install

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: PaperlessREST
        path: PaperlessREST/target/*.jar
